# Increase scrollback buffer size
set-option -g history-limit 50000

# Reduce escape-time to eliminate input latency (default is 500ms)
set -sg escape-time 10

set-option -g prefix Home

# tmux messages are displayed for 5 seconds
set -g display-time 5000

# Refresh 'status-left' and 'status-right' more often
set -g status-interval 5

# Upgrade $TERM
set -g default-terminal "screen-256color"

# Emacs key bindings in tmux command prompt (prefix + :) are better than
# vi keys, even for vim users
set -g status-keys emacs

# Hotkeys
bind -T copy-mode C-x send -X rectangle-toggle
bind-key -T copy-mode C-l send -X scroll-middle
bind-key -T copy-mode M-w send-keys -X copy-pipe

#bind -T copy-mode M-w send-keys -X copy-pipe-and-cancel "xclip -sel clip -i"


# List of plugins
#set -g @plugin 'tmux-plugins/tpm'
#set -g @plugin 'tmux-plugins/tmux-yank'

#set -g @yank_selection 'primary'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
#run '~/.tmux/plugins/tpm/tpm'
