(setq auto-mode-alist (cons '(".*\.sls" . yaml-mode) auto-mode-alist))
(setq auto-mode-alist (cons '(".*\.tmpl" . html-mode) auto-mode-alist))
(setq auto-mode-alist (cons '(".*\.twig" . html-mode) auto-mode-alist))
(setq auto-mode-alist (cons '(".*\.es6" . js-mode) auto-mode-alist))
(setq auto-mode-alist (cons '(".*\.es" . js-mode) auto-mode-alist))
(setq auto-mode-alist (cons '(".*\.jsx" . js-mode) auto-mode-alist))
